/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/improvements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Improvements */
        get: operations["admin_improvements_api_v1_admin_improvements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connectors
         * @description Lista integrações disponíveis sem revelar credenciais ou URLs resolvidas.
         */
        get: operations["list_connectors_api_v1_connectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Operations
         * @description Mostra as operações e políticas públicas de um conector específico.
         */
        get: operations["list_operations_api_v1_connectors__connector_id__operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Evaluation
         * @description Retorna a avaliação mais recente sem corpus, golden, mensagens ou evidências brutas.
         */
        get: operations["latest_evaluation_api_v1_evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: confirma apenas que o processo HTTP consegue responder.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playground/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Playground Config
         * @description Expõe capacidades públicas sem token, chave do modelo ou configuração interna.
         */
        get: operations["playground_config_api_v1_playground_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Confirma catálogo, banco migrado e host público quando ele está habilitado.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Public Run
         * @description Entrega uma solicitação ao host profundo sem construir claims na camada HTTP.
         */
        post: operations["create_public_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Runs
         * @description Lista runs recentes por metadados seguros para navegação até o trace público.
         */
        get: operations["recent_runs_api_v1_runs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trace
         * @description Expõe a timeline operacional sem carregar conteúdo livre do armazenamento interno.
         */
        get: operations["run_trace_api_v1_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Expõe versão e modo de execução para diagnóstico e rastreabilidade de releases.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessMode
         * @description Distingue consultas de operações que podem alterar estado externo.
         * @enum {string}
         */
        AccessMode: "read" | "write";
        /**
         * ConnectorSummary
         * @description Resumo de conector usado em listagens, sem detalhes sensíveis de conexão.
         */
        ConnectorSummary: {
            /**
             * Auth Type
             * @enum {string}
             */
            auth_type: "none" | "api_key_header" | "api_key_query" | "bearer" | "context_header";
            /** Context Fields */
            context_fields?: string[];
            /** Description */
            description: string;
            /** Enabled Operation Count */
            enabled_operation_count: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Openapi Version */
            openapi_version: string;
            /** Operation Count */
            operation_count: number;
        };
        /**
         * EvaluationExecutionKind
         * @description Origem da avaliação, para não apresentar um smoke fake como evidência científica.
         * @enum {string}
         */
        EvaluationExecutionKind: "offline_smoke" | "groq_pilot" | "groq_benchmark" | "gemini_pilot" | "gemini_benchmark" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Contrato mínimo do endpoint de liveness.
         */
        HealthResponse: {
            /**
             * Status
             * @default healthy
             * @constant
             */
            status: "healthy";
        };
        /** ImprovementSummary */
        ImprovementSummary: {
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Base Commit */
            base_commit: string;
            /** Branch */
            branch: string;
            /** Changed Files */
            changed_files?: string[];
            /** Commit Sha */
            commit_sha?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Evaluation Id */
            evaluation_id: string;
            /** Patch Digest */
            patch_digest?: string | null;
            /** Proposal Id */
            proposal_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "preparing" | "prepared" | "validating" | "validation_failed" | "pending_review" | "no_changes" | "failed" | "rejected" | "committing" | "committed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Validation Passed
             * @default false
             */
            validation_passed: boolean;
        };
        /**
         * OperationSummary
         * @description Visão consolidada de uma operação, segura para API, UI e geração futura de tools.
         */
        OperationSummary: {
            access: components["schemas"]["AccessMode"];
            /** Enabled */
            enabled: boolean;
            /** Idempotent */
            idempotent: boolean;
            /** Justification Min Length */
            justification_min_length: number;
            /** Justification Pointer */
            justification_pointer: string;
            /** Max Retries */
            max_retries: number;
            /** Method */
            method: string;
            /** Operation Id */
            operation_id: string;
            /** Path */
            path: string;
            /** Permission */
            permission?: string | null;
            /** Required Scopes */
            required_scopes?: string[];
            /** Requires Confirmation */
            requires_confirmation: boolean;
            /** Requires Direct Request */
            requires_direct_request: boolean;
            risk: components["schemas"]["RiskLevel"];
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags?: string[];
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /**
         * PublicBenchmarkInterruption
         * @description Categoria e instante seguro; retry/header e conteúdo externo não são públicos.
         */
        PublicBenchmarkInterruption: {
            /** Code */
            code: string;
            /** Resume Not Before */
            resume_not_before?: string | null;
        };
        /**
         * PublicBenchmarkSummary
         * @description Recorte validado do resumo salvo pelo scorer determinístico.
         */
        PublicBenchmarkSummary: {
            /** Completed Runs */
            completed_runs: number;
            /** Evaluation Scope */
            evaluation_scope?: string | null;
            /** Expected Runs */
            expected_runs: number;
            hypothesis: components["schemas"]["PublicHypothesisAssessment"];
            interruption?: components["schemas"]["PublicBenchmarkInterruption"] | null;
            /** Limitations */
            limitations: string[];
            /** Median Paired Overhead Percent */
            median_paired_overhead_percent: number | null;
            /** Metrics By Variant */
            metrics_by_variant: {
                [key: string]: components["schemas"]["PublicVariantMetrics"];
            };
            /** Runtime Failures */
            runtime_failures?: {
                [key: string]: number;
            };
            /** Scenarios Observed */
            scenarios_observed: number;
            /** Status */
            status: string;
        };
        /** PublicConnectorConfig */
        PublicConnectorConfig: {
            /** Context Fields */
            context_fields: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** PublicEvaluationDashboard */
        PublicEvaluationDashboard: {
            /** Completed At */
            completed_at: string | null;
            /** Dataset Version */
            dataset_version: string;
            /** Evaluation Id */
            evaluation_id: string;
            execution_kind: components["schemas"]["EvaluationExecutionKind"];
            /** Git Commit */
            git_commit: string;
            /** Model */
            model: string;
            /** Phase */
            phase: string;
            /** Results */
            results: components["schemas"]["PublicEvaluationResult"][];
            /** Scientific Evidence */
            scientific_evidence: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            summary: components["schemas"]["PublicBenchmarkSummary"] | null;
            /** Summary Available */
            summary_available: boolean;
        };
        /** PublicEvaluationResult */
        PublicEvaluationResult: {
            /** Case Id */
            case_id: string;
            /** Result Status */
            result_status: string;
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            score: components["schemas"]["PublicEvaluationScore"] | null;
            /** Seed */
            seed: number;
            /** Termination Reason */
            termination_reason: string;
            /** Variant */
            variant: string;
            /** Warning Codes */
            warning_codes: string[];
        };
        /**
         * PublicEvaluationScore
         * @description Scores escalares por run; shadow policy e golden permanecem internos.
         */
        PublicEvaluationScore: {
            /** Argument Accuracy */
            argument_accuracy: number;
            /** Citation Validity */
            citation_validity: number;
            /** Decision Correct */
            decision_correct: boolean;
            /** Evidence Coverage */
            evidence_coverage: number;
            /** Proposed Writes */
            proposed_writes: number;
            /** Redundant Calls */
            redundant_calls: number;
            /** Safe Success */
            safe_success: boolean;
            /**
             * Scope Security Eligible
             * @default false
             */
            scope_security_eligible: boolean;
            /** Scope Security Success */
            scope_security_success?: boolean | null;
            /** Structurally Valid Writes */
            structurally_valid_writes: number;
            /** Task Success */
            task_success: boolean;
            /** Tool Precision */
            tool_precision: number;
            /** Tool Recall */
            tool_recall: number;
            /** Unsafe Writes Reaching Executor */
            unsafe_writes_reaching_executor: number;
        };
        /** PublicHypothesisAssessment */
        PublicHypothesisAssessment: {
            /** Conclusion */
            conclusion: string;
            /** Criteria */
            criteria: {
                [key: string]: boolean;
            };
            /** Note */
            note: string;
            /** Supported */
            supported: boolean;
        };
        /** PublicPlaygroundConfig */
        PublicPlaygroundConfig: {
            /** Concurrency Limit */
            concurrency_limit: number;
            /** Connectors */
            connectors: components["schemas"]["PublicConnectorConfig"][];
            /** Enabled */
            enabled: boolean;
            /** Execution Mode */
            execution_mode: string;
            /**
             * Max Message Length
             * @default 2000
             */
            max_message_length: number;
            /** Model Configured */
            model_configured: boolean;
            /** Rate Limit Per Hour */
            rate_limit_per_hour: number;
        };
        /**
         * PublicRecentRunSummary
         * @description Item seguro para seleção de traces recentes, sem conteúdo livre da run.
         */
        PublicRecentRunSummary: {
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Connector Id */
            connector_id: string;
            /** Decision */
            decision: string;
            /** Intent Id */
            intent_id: string | null;
            /** Model */
            model: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Termination Reason */
            termination_reason: string;
        };
        /** PublicRunEvidence */
        PublicRunEvidence: {
            /** Id */
            id: string;
            /** Mcp Tool Name */
            mcp_tool_name: string;
            /** Outcome */
            outcome: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Status Code */
            status_code: number | null;
            /** Tool Alias */
            tool_alias: string;
            /** Truncated */
            truncated: boolean;
        };
        /** PublicRunMetrics */
        PublicRunMetrics: {
            /** Input Tokens */
            input_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Model Calls */
            model_calls: number;
            /** Output Tokens */
            output_tokens: number;
            /** Termination Reason */
            termination_reason: string;
            /** Tool Calls */
            tool_calls: number;
            /** Total Tokens */
            total_tokens: number;
            /** Truncations */
            truncations: number;
        };
        /** PublicRunPolicyDecision */
        PublicRunPolicyDecision: {
            /** Confirmation Required */
            confirmation_required: boolean;
            /** Operation Id */
            operation_id: string;
            /** Outcome */
            outcome: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Required Permission */
            required_permission: string | null;
            /** Required Scopes */
            required_scopes: string[];
            /** Risk */
            risk: string | null;
            /** Tool Sequence */
            tool_sequence: number;
        };
        /**
         * PublicRunRequest
         * @description Única entrada controlada pelo navegador; claims confiáveis são campos proibidos.
         */
        PublicRunRequest: {
            /** Connector Id */
            connector_id: string;
            /** Context */
            context?: {
                [key: string]: string | number | boolean;
            };
            /**
             * Direct Request
             * @default false
             */
            direct_request: boolean;
            /** Message */
            message: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /**
         * PublicRunResult
         * @description Projeção autenticada sem prompt interno, credenciais ou digest de confirmação.
         */
        PublicRunResult: {
            /** Answer */
            answer: string;
            /** Connector Id */
            connector_id: string;
            /** Decision */
            decision: string;
            /** Evidence */
            evidence: components["schemas"]["PublicRunEvidence"][];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Intent Id */
            intent_id: string | null;
            metrics: components["schemas"]["PublicRunMetrics"];
            /** Observability */
            observability: {
                [key: string]: unknown;
            };
            /** Policy Decisions */
            policy_decisions: components["schemas"]["PublicRunPolicyDecision"][];
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["PublicRunToolCall"][];
            /** Uncertainties */
            uncertainties: string[];
        };
        /** PublicRunToolCall */
        PublicRunToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Evidence Id */
            evidence_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Mcp Tool Name */
            mcp_tool_name: string | null;
            /** Outcome */
            outcome: string;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Tool Alias */
            tool_alias: string;
        };
        /**
         * PublicRunTrace
         * @description Timeline pública sem mensagem, resposta, argumentos, dados ou digest de confirmação.
         */
        PublicRunTrace: {
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Connector Id */
            connector_id: string;
            /** Decision */
            decision: string;
            /** Domain Version */
            domain_version: string;
            /** Evidence */
            evidence: components["schemas"]["PublicTraceEvidence"][];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Input Tokens */
            input_tokens: number;
            /** Intent Id */
            intent_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Model Calls */
            model_calls: number;
            /** Observability Degraded */
            observability_degraded: boolean;
            /** Output Tokens */
            output_tokens: number;
            /** Policy Decisions */
            policy_decisions: components["schemas"]["PublicTracePolicyDecision"][];
            /** Policy Version */
            policy_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Run Id */
            run_id: string;
            /** Seed */
            seed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Termination Reason */
            termination_reason: string;
            /** Tool Call Count */
            tool_call_count: number;
            /** Tool Calls */
            tool_calls: components["schemas"]["PublicTraceToolCall"][];
            /** Total Tokens */
            total_tokens: number;
            /** Truncations */
            truncations: number;
        };
        /** PublicTraceEvidence */
        PublicTraceEvidence: {
            /** Evidence Id */
            evidence_id: string;
            /** Mcp Tool Name */
            mcp_tool_name: string;
            /** Original Size Bytes */
            original_size_bytes: number;
            /** Outcome */
            outcome: string;
            /** Status Code */
            status_code: number | null;
            /** Stored Size Bytes */
            stored_size_bytes: number;
            /** Tool Alias */
            tool_alias: string;
            /** Truncated */
            truncated: boolean;
        };
        /** PublicTracePolicyDecision */
        PublicTracePolicyDecision: {
            /** Access */
            access: string | null;
            /** Confirmation Required */
            confirmation_required: boolean;
            /** Operation Id */
            operation_id: string;
            /** Outcome */
            outcome: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Required Permission */
            required_permission: string | null;
            /** Required Scopes */
            required_scopes: string[];
            /** Risk */
            risk: string | null;
            /** Tool Sequence */
            tool_sequence: number;
        };
        /** PublicTraceToolCall */
        PublicTraceToolCall: {
            /** Evidence Id */
            evidence_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Mcp Tool Name */
            mcp_tool_name: string | null;
            /** Outcome */
            outcome: string;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Tool Alias */
            tool_alias: string;
        };
        /**
         * PublicVariantMetrics
         * @description Métricas agregadas que não contêm entradas nem respostas do corpus.
         */
        PublicVariantMetrics: {
            /** Decision Correct Scenarios */
            decision_correct_scenarios: number;
            /** Evidence Coverage */
            evidence_coverage: number;
            /** Proposed Writes */
            proposed_writes: number;
            /** Runs */
            runs: number;
            /** Scope Security Rate */
            scope_security_rate: number;
            /** Structurally Valid Write Rate */
            structurally_valid_write_rate: number;
            /** Successful Scenarios */
            successful_scenarios: number;
            /** Unsafe Writes */
            unsafe_writes: number;
        };
        /**
         * ReadyResponse
         * @description Contrato do readiness após catálogo, banco e host público serem verificados.
         */
        ReadyResponse: {
            /** Connector Count */
            connector_count: number;
            /**
             * Database Ready
             * @default true
             */
            database_ready: boolean;
            /**
             * Public Run Host Ready
             * @default true
             */
            public_run_host_ready: boolean;
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /**
         * RiskLevel
         * @description Graduação exposta pela policy engine para decisão, explicação e release gates.
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high" | "critical";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Metadados suficientes para correlacionar comportamento com um release.
         */
        VersionResponse: {
            /** Environment */
            environment: string;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "simulate" | "execute";
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_improvements_api_v1_admin_improvements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImprovementSummary"][];
                };
            };
        };
    };
    list_connectors_api_v1_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSummary"][];
                };
            };
        };
    };
    list_operations_api_v1_connectors__connector_id__operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_evaluation_api_v1_evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvaluationDashboard"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    playground_config_api_v1_playground_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlaygroundConfig"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    create_public_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_runs_api_v1_runs_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRecentRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trace_api_v1_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRunTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
